disabled_rules:
  - trailing_whitespace
  - statement_position
  - identifier_name
  - unused_closure_parameter
  - multiple_closures_with_trailing_closure
  - type_body_length
  - function_parameter_count
  - force_cast

excluded:
  - Carthage
  - Pods
  - Package.swift
  
force_try: warning
    
function_body_length:
    warning: 120
    error: 150
    
file_length:
    warning: 1000
    error: 1500
    
cyclomatic_complexity: 25
